CREATE DATABASE IF NOT EXISTS study;
USE study;

CREATE TABLE  IF NOT EXISTS `author` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `name` VARCHAR(20) DEFAULT NULL COMMENT '姓名',
  `dynasty` VARCHAR(10) DEFAULT NULL COMMENT '朝代',
  `introduction` BLOB COMMENT '简介',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='作者表';

CREATE TABLE  IF NOT EXISTS `poem`  (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `title` VARCHAR(100) DEFAULT NULL COMMENT '题目',
  `author` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '作者',
  `content` BLOB COMMENT '内容',
  `annotation` BLOB COMMENT '注释',
  `appreciate` BLOB COMMENT '赏析',
  `type` TINYINT(4) DEFAULT NULL COMMENT '类型',
  PRIMARY KEY (`id`),
  KEY `author_fk` (`author`),
  CONSTRAINT `author_fk` FOREIGN KEY (`author`) REFERENCES `author` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;E=InnoDB DEFAULT CHARSET=utf8 COMMENT='作品表';