server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/study?serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #默认org.apache.tomcat.jdbc.pool.DataSource
   # type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  typeAliasesPackage: com.my.entity
  mapperLocations: classpath:mybatis/*.xml