server:
  port: 8888


#mvc:
#  view:
#    prefix : /webapp/views/
#    suffix : .html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/study?serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #默认org.apache.tomcat.jdbc.pool.DataSource
   # type: com.alibaba.druid.pool.DruidDataSource
  groovy:
    template:
      request-context-attribute: req
      suffix: .ftl
      charset: UTF-8
      content-type: text/html


mybatis:
  typeAliasesPackage: com.my.entity
  mapperLocations: classpath:mybatis/*.xml


site:
  auth:
    firstName: hello
    lastName: haha

#
#freemarker:
#  request-context-attribute: req  #req访问request
#  　　 suffix: .ftl  #后缀名
#    content-type: text/html
#    enabled: true
#    cache: false #缓存配置
#    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
#    charset: UTF-8 #编码格式
#    settings:
#      number_format: '0.##'   #数字格式化，无小数点